# Generated by Django 2.2.2 on 2020-11-25 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201122_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'username'},
        ),
    ]
