# Generated by Django 2.2.2 on 2020-11-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201125_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='app.Like'),
        ),
    ]
