# Generated by Django 2.2.2 on 2020-11-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201125_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Comment'),
        ),
    ]
