# Generated by Django 2.2.2 on 2020-11-25 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201125_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.Like'),
        ),
        migrations.AddField(
            model_name='like',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
