# Generated by Django 2.2.2 on 2020-11-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0009_auto_20201125_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test_image')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011)], default=2020, verbose_name='テスト実施年度')),
                ('title', models.CharField(choices=[('中間テスト', '中間テスト'), ('期末テスト', '期末テスト'), ('レポート', 'レポート'), ('小テスト', '小テスト'), ('授業資料', '授業資料'), ('その他', 'その他')], default='中間テスト', max_length=50)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='テストへのコメント')),
                ('like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Like')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
