# Generated by Django 2.2.2 on 2020-11-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_image',
            name='like',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Like'),
        ),
    ]
