# Generated by Django 2.2.2 on 2020-12-02 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_share', '0002_auto_20201130_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_image',
            name='like',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Like'),
        ),
    ]
